from . import website
from . import fo_top_slider
from . import res_config_settings
from . import product_offers
from . import top_products
from . import our_tips
from . import client_reviews
from . import faqs
from . import prescription
from . import quote