from . import website
from . import fo_top_slider
from . import res_config_settings
from . import product_offers
from . import top_products
from . import our_tips
from . import client_reviews
from . import faqs
from . import branch_offices
from . import contact
from . import prescription
from . import quote
from . import pos_config
from . import pos_order
from . import account_journal_extension
from . import account_move_extension
from . import multi_branch_extension
from . import odoo_fe_panama_extension
from . import sale_report